"""
Secure-MaintAI — Role-Sensitive Security Policy Engine.

Per engineering rules:
- Rule 16: Required flow is ML Prediction -> Security Correlation -> Identity Context -> Policy Engine -> Authorized Action.
- Rule 19: Surgical isolation with protected processes, protected workloads, emergency kill switch, and rollback.
- Rule 20: Differentiates STUDENT, RESEARCHER, IT_OPERATOR, ADMIN contexts.
- Rule 29: Satisfies scenarios for Benign Compute vs Cryptojacking vs Hardware Failure vs IdP Outage.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field

from backend.core.logging import get_logger
from backend.schemas.idp import IdPIdentityContext, IdPWorkstationContext, WorkloadType
from backend.schemas.security_event import SecurityEventSeverity
from security.correlation_engine import CorrelatedIncident

logger = get_logger("policy_engine")


class PolicyDecisionType(str, Enum):
    """Authorized policy outcomes determined by the policy engine."""

    ALLOW_LEGITIMATE_RESEARCH = "ALLOW_LEGITIMATE_RESEARCH"
    SCHEDULE_MAINTENANCE = "SCHEDULE_MAINTENANCE"
    ALERT_SOC_ONLY = "ALERT_SOC_ONLY"
    SURGICAL_PROCESS_CONTAINMENT = "SURGICAL_PROCESS_CONTAINMENT"
    SURGICAL_NETWORK_ISOLATION = "SURGICAL_NETWORK_ISOLATION"
    ACCOUNT_LOCKOUT = "ACCOUNT_LOCKOUT"
    REQUIRE_HUMAN_APPROVAL = "REQUIRE_HUMAN_APPROVAL"


class PolicyEvaluationResult(BaseModel):
    """Formal policy decision generated by the policy engine."""

    workstation_id: UUID
    user_context: IdPIdentityContext
    workstation_context: IdPWorkstationContext
    correlated_incident: CorrelatedIncident
    decision: PolicyDecisionType
    playbook_to_execute: str
    target_pids: list[int] = Field(default_factory=list)
    target_ports: list[int] = Field(default_factory=list)
    preserve_workloads: list[str] = Field(
        default_factory=list,
        description="Protected research job IDs or processes exempt from termination.",
    )
    requires_human_approval: bool = False
    reason: str
    policy_rules_triggered: list[str] = Field(default_factory=list)
    kill_switch_active: bool = False
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SecurityPolicyEngine:
    """
    Evaluates correlation results against university identity context,
    enforcing role-sensitive surgical policies and fail-safe boundaries.
    """

    def __init__(self, emergency_kill_switch: bool = False) -> None:
        self._kill_switch: bool = emergency_kill_switch

    def set_emergency_kill_switch(self, active: bool) -> None:
        """
        Emergency kill switch (Rule 19): When active, all automated containment
        and isolation actions are immediately suppressed to prevent accidental disruption.
        """
        self._kill_switch = active
        logger.warning("emergency_kill_switch_toggled", active=active)

    @property
    def is_kill_switch_active(self) -> bool:
        return self._kill_switch

    def evaluate_policy(
        self,
        incident: CorrelatedIncident,
        user_context: IdPIdentityContext,
        ws_context: IdPWorkstationContext,
    ) -> PolicyEvaluationResult:
        """
        Evaluate correlation findings against user role, environment type,
        and registered workloads.
        """
        rules_triggered: list[str] = []
        target_pids: list[int] = []
        target_ports: list[int] = []
        preserve_workloads: list[str] = []
        requires_human_approval: bool = False

        # Extract malicious target ports from incident evidence if present (e.g. 3333, 4444)
        for ev in incident.evidence:
            for port in [3333, 4444, 5555, 8333, 8008]:
                if f":{port}" in ev or f"port {port}" in ev.lower():
                    if port not in target_ports:
                        target_ports.append(port)

        # -------------------------------------------------------------
        # 1. EMERGENCY KILL SWITCH CHECK (Rule 19)
        # -------------------------------------------------------------
        if self._kill_switch:
            rules_triggered.append("RULE_KILL_SWITCH_ACTIVE")
            return PolicyEvaluationResult(
                workstation_id=incident.workstation_id,
                user_context=user_context,
                workstation_context=ws_context,
                correlated_incident=incident,
                decision=PolicyDecisionType.ALERT_SOC_ONLY,
                playbook_to_execute="PLAYBOOK_01_ALERT_ONLY",
                target_pids=[],
                target_ports=target_ports,
                preserve_workloads=[w.job_id for w in ws_context.active_workloads],
                requires_human_approval=True,
                reason="Emergency kill switch is active. Automated destructive containment is suppressed; alert routed to SOC.",
                policy_rules_triggered=rules_triggered,
                kill_switch_active=True,
            )

        user_role = user_context.role.upper()
        has_active_research = any(
            w.is_active and w.workload_type in (WorkloadType.HPC_SIMULATION, WorkloadType.MODEL_TRAINING)
            for w in ws_context.active_workloads
        )

        # -------------------------------------------------------------
        # 2. IdP OUTAGE SAFE FALLBACK CHECK (Rule 18, 25, Rule 29 Scenario 5)
        # -------------------------------------------------------------
        if user_context.is_fallback and incident.is_threat:
            rules_triggered.append("RULE_IDP_OUTAGE_SAFE_FALLBACK")
            sev_str = str(incident.severity.value if hasattr(incident.severity, 'value') else incident.severity).upper()
            requires_human_approval = sev_str in ("HIGH", "CRITICAL")
            if requires_human_approval:
                return PolicyEvaluationResult(
                    workstation_id=incident.workstation_id,
                    user_context=user_context,
                    workstation_context=ws_context,
                    correlated_incident=incident,
                    decision=PolicyDecisionType.REQUIRE_HUMAN_APPROVAL,
                    playbook_to_execute="PLAYBOOK_01_ALERT_ONLY",
                    target_pids=target_pids,
                    target_ports=target_ports,
                    preserve_workloads=[],
                    requires_human_approval=True,
                    reason="Identity provider is unreachable. Operating under conservative fail-soft policy: high-risk containment queued for human SOC approval.",
                    policy_rules_triggered=rules_triggered,
                )

        # -------------------------------------------------------------
        # 3. BENIGN HIGH COMPUTE / RESEARCH SIMULATION (Rule 20, Rule 29 Scenario 3)
        # -------------------------------------------------------------
        if (
            incident.incident_category in ("BENIGN_HIGH_COMPUTE", "BENIGN_HIGH_LOAD")
            or (has_active_research and not incident.is_threat)
        ):
            rules_triggered.append("RULE_BENIGN_RESEARCH_COMPUTE")
            for w in ws_context.active_workloads:
                if w.is_active:
                    preserve_workloads.append(w.job_id)

            return PolicyEvaluationResult(
                workstation_id=incident.workstation_id,
                user_context=user_context,
                workstation_context=ws_context,
                correlated_incident=incident,
                decision=PolicyDecisionType.ALLOW_LEGITIMATE_RESEARCH,
                playbook_to_execute="PLAYBOOK_04_MAINTENANCE",
                target_pids=[],
                target_ports=[],
                preserve_workloads=preserve_workloads,
                requires_human_approval=False,
                reason=(
                    f"Workload authorized under {user_role} context ({ws_context.lab or 'Research'}). "
                    "High resource utilization validated as legitimate compute; containment suppressed."
                ),
                policy_rules_triggered=rules_triggered,
            )

        # -------------------------------------------------------------
        # 4. HARDWARE DEGRADATION / TECHNICAL FAILURE (Rule 29 Scenario 1)
        # -------------------------------------------------------------
        if (
            incident.incident_category in ("HARDWARE_DEGRADATION", "TECHNICAL_FAULT")
            or not incident.is_threat
        ):
            rules_triggered.append("RULE_TECHNICAL_MAINTENANCE")
            return PolicyEvaluationResult(
                workstation_id=incident.workstation_id,
                user_context=user_context,
                workstation_context=ws_context,
                correlated_incident=incident,
                decision=PolicyDecisionType.SCHEDULE_MAINTENANCE,
                playbook_to_execute="PLAYBOOK_04_MAINTENANCE",
                target_pids=[],
                target_ports=[],
                preserve_workloads=[w.job_id for w in ws_context.active_workloads],
                requires_human_approval=False,
                reason="Technical performance degradation or hardware fault diagnosed. Maintenance advisory dispatched without security isolation.",
                policy_rules_triggered=rules_triggered,
            )

        # -------------------------------------------------------------
        # 4. CRYPTOJACKING DETECTION — ROLE-SENSITIVE RESOLUTION (Rule 20, Rule 29 Scenario 2 & 3)
        # -------------------------------------------------------------
        if incident.incident_category == "CRYPTOJACKING":
            if user_role == "RESEARCHER" or has_active_research:
                # Researcher context: Surgical targeting only (terminate miner, preserve research workload)
                rules_triggered.append("RULE_RESEARCHER_SURGICAL_CONTAINMENT")
                preserve_workloads = [w.job_id for w in ws_context.active_workloads if w.is_active]
                
                # In research environment, isolate the rogue stratum network connection/miner process
                # rather than shutting down the host or terminating the simulation
                return PolicyEvaluationResult(
                    workstation_id=incident.workstation_id,
                    user_context=user_context,
                    workstation_context=ws_context,
                    correlated_incident=incident,
                    decision=PolicyDecisionType.SURGICAL_PROCESS_CONTAINMENT,
                    playbook_to_execute="PLAYBOOK_02_PROCESS_CONTAINMENT",
                    target_pids=target_pids,
                    target_ports=target_ports,
                    preserve_workloads=preserve_workloads,
                    requires_human_approval=False,
                    reason=(
                        "Cryptojacking detected on Researcher workstation. Executing surgical process "
                        f"containment and port blocking to terminate miner while preserving active research jobs {preserve_workloads}."
                    ),
                    policy_rules_triggered=rules_triggered,
                )
            else:
                # Student / Generic Lab PC: Swift surgical isolation
                rules_triggered.append("RULE_STUDENT_CRYPTOJACKING_ISOLATION")
                return PolicyEvaluationResult(
                    workstation_id=incident.workstation_id,
                    user_context=user_context,
                    workstation_context=ws_context,
                    correlated_incident=incident,
                    decision=PolicyDecisionType.SURGICAL_NETWORK_ISOLATION,
                    playbook_to_execute="PLAYBOOK_03_SURGICAL_ISOLATION",
                    target_pids=target_pids,
                    target_ports=target_ports,
                    preserve_workloads=[],
                    requires_human_approval=False,
                    reason="Unauthorized cryptojacking mining activity confirmed on standard workstation. Authorizing surgical network isolation.",
                    policy_rules_triggered=rules_triggered,
                )

        # -------------------------------------------------------------
        # 5. APT INTRUSION / PRIVILEGE ESCALATION / CREDENTIAL DUMPING (Rule 29 Scenario 4)
        # -------------------------------------------------------------
        if incident.incident_category in ("APT_INTRUSION", "DATA_EXFILTRATION"):
            rules_triggered.append("RULE_APT_SURGICAL_ISOLATION")
            return PolicyEvaluationResult(
                workstation_id=incident.workstation_id,
                user_context=user_context,
                workstation_context=ws_context,
                correlated_incident=incident,
                decision=PolicyDecisionType.SURGICAL_NETWORK_ISOLATION,
                playbook_to_execute="PLAYBOOK_03_SURGICAL_ISOLATION",
                target_pids=target_pids,
                target_ports=target_ports,
                preserve_workloads=[],
                requires_human_approval=False,
                reason="Severe security threat (APT intrusion / credential dumping / unauthorized exfiltration). Authorizing immediate host containment.",
                policy_rules_triggered=rules_triggered,
            )

        # -------------------------------------------------------------
        # 6. BRUTE FORCE / UNAUTHORIZED ACCESS
        # -------------------------------------------------------------
        if incident.incident_category == "BRUTE_FORCE_ATTACK":
            rules_triggered.append("RULE_BRUTE_FORCE_LOCKOUT")
            return PolicyEvaluationResult(
                workstation_id=incident.workstation_id,
                user_context=user_context,
                workstation_context=ws_context,
                correlated_incident=incident,
                decision=PolicyDecisionType.ACCOUNT_LOCKOUT,
                playbook_to_execute="PLAYBOOK_05_ACCOUNT_RESPONSE",
                target_pids=[],
                target_ports=[],
                preserve_workloads=[],
                requires_human_approval=False,
                reason="Multiple authentication failures and brute force signature detected. Authorizing temporary account lockout.",
                policy_rules_triggered=rules_triggered,
            )

        # -------------------------------------------------------------
        # 7. DEFAULT / IdP FALLBACK POLICY (Rule 18, 25, Rule 29 Scenario 5)
        # -------------------------------------------------------------
        if user_context.is_fallback:
            rules_triggered.append("RULE_IDP_OUTAGE_SAFE_FALLBACK")
            requires_human_approval = incident.severity in ("HIGH", "CRITICAL")
            return PolicyEvaluationResult(
                workstation_id=incident.workstation_id,
                user_context=user_context,
                workstation_context=ws_context,
                correlated_incident=incident,
                decision=(
                    PolicyDecisionType.REQUIRE_HUMAN_APPROVAL
                    if requires_human_approval
                    else PolicyDecisionType.ALERT_SOC_ONLY
                ),
                playbook_to_execute="PLAYBOOK_01_ALERT_ONLY",
                target_pids=target_pids,
                target_ports=target_ports,
                preserve_workloads=[],
                requires_human_approval=requires_human_approval,
                reason="Identity provider is unreachable. Operating under conservative fail-soft policy: high-risk containment queued for human SOC approval.",
                policy_rules_triggered=rules_triggered,
            )

        # Default catch-all
        rules_triggered.append("RULE_DEFAULT_ALERT")
        return PolicyEvaluationResult(
            workstation_id=incident.workstation_id,
            user_context=user_context,
            workstation_context=ws_context,
            correlated_incident=incident,
            decision=PolicyDecisionType.ALERT_SOC_ONLY,
            playbook_to_execute="PLAYBOOK_01_ALERT_ONLY",
            target_pids=target_pids,
            target_ports=target_ports,
            preserve_workloads=[],
            requires_human_approval=False,
            reason=f"Security event category '{incident.incident_category}' logged for SOC review.",
            policy_rules_triggered=rules_triggered,
        )


# Global singleton instance
policy_engine = SecurityPolicyEngine()
