"""
Secure-MaintAI — Alert Model.

Per implementation plan Section 21: alert lifecycle.
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Index, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from backend.models.user import UserAccount
    from backend.models.workstation import Workstation


class Alert(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Alert generated by the detection pipeline."""

    __tablename__ = "alert"

    source_type: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        comment="ANOMALY_DETECTION, SECURITY_EVENT, AGENT_HEALTH, SYSTEM, MANUAL",
    )
    source_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid,
        nullable=True,
        comment="FK to the source record that generated this alert",
    )
    workstation_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid,
        ForeignKey("workstation.id"),
        nullable=True,
        comment="Affected workstation",
    )
    acknowledged_by: Mapped[uuid.UUID | None] = mapped_column(
        Uuid,
        ForeignKey("user_account.id"),
        nullable=True,
        comment="User who acknowledged the alert",
    )
    severity: Mapped[str] = mapped_column(String(16), nullable=False, comment="LOW, MEDIUM, HIGH, CRITICAL")
    status: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        default="OPEN",
        comment="OPEN, ACKNOWLEDGED, INVESTIGATING, CONTAINED, RESOLVED",
    )
    title: Mapped[str] = mapped_column(String(256), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    workstation: Mapped["Workstation | None"] = relationship("Workstation", lazy="selectin")
    acknowledged_by_user: Mapped["UserAccount | None"] = relationship(
        "UserAccount", foreign_keys=[acknowledged_by], lazy="selectin"
    )

    # Property aliases
    @property
    def alert_title(self) -> str:
        return self.title

    @property
    def alert_message(self) -> str:
        return self.description

    @property
    def priority(self) -> str:
        return self.severity

    @property
    def alert_status(self) -> str:
        return self.status

    @property
    def generated_at(self) -> datetime:
        return self.created_at

    __table_args__ = (
        Index("ix_alert_status", "status"),
        Index("ix_alert_severity", "severity"),
        Index("ix_alert_created", "created_at"),
        Index("ix_alert_workstation", "workstation_id"),
    )

    def __repr__(self) -> str:
        return f"<Alert(title='{self.title}', severity={self.severity}, status={self.status})>"
