"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import {
  FileText,
  Calendar,
  Clock,
  Download,
  Server,
  AlertTriangle,
  PlusCircle,
  Shield,
  ShieldCheck,
  CheckCircle2,
  ChevronDown,
  Cpu,
  Layers,
  HardDrive,
  Activity,
  Mail,
  Check,
  X,
} from "lucide-react";
import { DonutChart } from "@/components/charts/DonutChart";
import { LineChart } from "@/components/charts/LineChart";
import {
  MOCK_EXECUTIVE_REPORT_KPIS,
  MOCK_REPORT_HEALTH_OVERVIEW,
  MOCK_REPORT_UPTIME_TREND,
  MOCK_REPORT_ALERTS_OVERVIEW,
  MOCK_REPORT_SECURITY_KPIS,
  MOCK_TOP_THREATS_WEEK,
  MOCK_TOP_ALERT_CATEGORIES,
  MOCK_RESOURCE_UTILIZATION,
  MOCK_REPORT_RECOMMENDATIONS,
  getReportSummary,
  downloadReportExport,
} from "@/lib/api";

export default function ReportsPage() {
  // Sub-toolbar state
  const [dateRange, setDateRange] = useState("Sep 10, 2026 - Sep 16, 2026");
  const [showDateDropdown, setShowDateDropdown] = useState(false);
  const [showScheduleModal, setShowScheduleModal] = useState(false);
  const [showExportDropdown, setShowExportDropdown] = useState(false);
  const [feedbackToast, setFeedbackToast] = useState<string | null>(null);
  const [kpis, setKpis] = useState(MOCK_EXECUTIVE_REPORT_KPIS);

  // Live Executive Summary data fetch with dual-mode fallback
  useEffect(() => {
    let isMounted = true;
    async function loadReportSummary() {
      try {
        const summary = await getReportSummary();
        if (isMounted && summary) {
          setKpis({
            total_devices: summary.fleet_total_workstations,
            total_devices_change: "+12 from last week",
            system_uptime: summary.fleet_uptime_percentage,
            system_uptime_change: "+1.02% vs SLA",
            critical_alerts: summary.critical_alerts,
            critical_alerts_change: "-3 from last week",
            security_score: Math.min(
              100,
              Math.round(
                summary.fleet_uptime_percentage * 0.7 +
                  Math.max(0, 100 - summary.active_security_threats * 5) * 0.3
              )
            ),
            security_score_change: "+8 points from last week",
          });
        }
      } catch {
        // Retain default mock baseline
      }
    }
    loadReportSummary();
    return () => {
      isMounted = false;
    };
  }, []);

  // Uptime trend filter state
  const [uptimeWindow, setUptimeWindow] = useState<"7 Days" | "14 Days" | "30 Days">("7 Days");

  // Schedule Report Form
  const [scheduleEmail, setScheduleEmail] = useState("admin@university.edu, secops@university.edu");
  const [scheduleCadence, setScheduleCadence] = useState("Weekly");
  const [scheduleTime, setScheduleTime] = useState("Wednesdays at 10:00 AM AST");
  const [scheduleIncludePdf, setScheduleIncludePdf] = useState(true);
  const [scheduleIncludeCsv, setScheduleIncludeCsv] = useState(true);

  // Donut chart data matching users/page.tsx pattern
  const alertsDonutData = MOCK_REPORT_ALERTS_OVERVIEW.slices.map((slice) => ({
    label: slice.label,
    value: slice.count,
    color: slice.color,
  }));

  // Handle Export Download (live streaming CSV with graceful client fallback)
  const handleTriggerExport = async (format: "pdf" | "excel" | "powerpoint" | "csv") => {
    setShowExportDropdown(false);

    if (format === "csv") {
      try {
        const blob = await downloadReportExport("csv");
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `secure-maintai-executive-report-${new Date().toISOString().slice(0, 10)}.csv`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
        setFeedbackToast("Live CSV Forensic Report downloaded successfully from backend.");
      } catch {
        // Fallback to client-side CSV generator if offline
        const csvRows = [
          ["Secure-MaintAI Infrastructure & Security Report"],
          ["Report Period", dateRange],
          ["Generated On", "Sep 16, 2026 - 10:30 AM AST"],
          ["Generated By", "Secure-MaintAI Platform"],
          [],
          ["Executive KPI", "Value", "Delta"],
          ["Total Devices", kpis.total_devices.toString(), kpis.total_devices_change],
          ["System Uptime", `${kpis.system_uptime}%`, kpis.system_uptime_change],
          ["Critical Alerts", kpis.critical_alerts.toString(), kpis.critical_alerts_change],
          ["Security Score", `${kpis.security_score} / 100`, kpis.security_score_change],
          [],
          ["Top Threat Name", "Severity", "Occurrences", "Status", "First Detected"],
          ...MOCK_TOP_THREATS_WEEK.map((t) => [
            t.threat_name,
            t.severity,
            t.occurrences.toString(),
            t.status,
            t.first_detected,
          ]),
          [],
          ["Alert Category", "Alert Count"],
          ...MOCK_TOP_ALERT_CATEGORIES.map((c) => [c.category, c.count.toString()]),
        ];

        const csvContent =
          "data:text/csv;charset=utf-8," +
          csvRows.map((e) => e.map((val) => `"${val}"`).join(",")).join("\n");
        const encodedUri = encodeURI(csvContent);
        const link = document.createElement("a");
        link.setAttribute("href", encodedUri);
        link.setAttribute(
          "download",
          `secure-maintai-executive-report-${new Date().toISOString().slice(0, 10)}.csv`
        );
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);

        setFeedbackToast("CSV Report downloaded successfully.");
      }
    } else if (format === "pdf") {
      window.print();
      setFeedbackToast("Print / PDF compilation dialog opened.");
    } else {
      setFeedbackToast(
        `Compiled and initiated download for ${format.toUpperCase()} executive summary.`
      );
    }

    setTimeout(() => setFeedbackToast(null), 4000);
  };

  const handleSaveSchedule = (e: React.FormEvent) => {
    e.preventDefault();
    setShowScheduleModal(false);
    setFeedbackToast(`Automated report schedule saved for ${scheduleCadence} distribution.`);
    setTimeout(() => setFeedbackToast(null), 4000);
  };

  return (
    <div className="space-y-6">
      {/* Toast Feedback Notification */}
      {feedbackToast && (
        <div className="p-3.5 rounded-xl bg-emerald-950/80 border border-emerald-500/50 text-emerald-300 text-xs flex items-center justify-between shadow-lg shadow-emerald-950/40 animate-fade-in">
          <div className="flex items-center gap-2.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-400 flex-shrink-0" />
            <span>{feedbackToast}</span>
          </div>
          <button onClick={() => setFeedbackToast(null)} className="text-emerald-400 hover:text-white cursor-pointer">
            <X className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* In-Page Sub-Toolbar matching Reports page.jpeg */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
        {/* Date Range Selector Dropdown */}
        <div className="relative">
          <button
            onClick={() => setShowDateDropdown(!showDateDropdown)}
            className="px-3.5 py-2 rounded-xl bg-slate-900/80 border border-slate-800 hover:border-slate-700 text-xs font-medium text-slate-200 flex items-center gap-2 transition-colors cursor-pointer"
          >
            <Calendar className="w-3.5 h-3.5 text-slate-400" />
            <span>{dateRange}</span>
            <ChevronDown className="w-3.5 h-3.5 text-slate-400 ml-1" />
          </button>

          {showDateDropdown && (
            <div className="absolute left-0 top-11 w-64 bg-slate-900 border border-slate-700 rounded-xl shadow-2xl z-30 py-1.5 text-xs animate-fade-in">
              {[
                "Sep 10, 2026 - Sep 16, 2026",
                "Sep 03, 2026 - Sep 16, 2026",
                "Aug 17, 2026 - Sep 16, 2026",
                "Sep 01, 2026 - Sep 16, 2026",
              ].map((range) => (
                <button
                  key={range}
                  onClick={() => {
                    setDateRange(range);
                    setShowDateDropdown(false);
                    setFeedbackToast(`Report period updated to ${range}.`);
                    setTimeout(() => setFeedbackToast(null), 3000);
                  }}
                  className={`w-full px-3.5 py-2 text-left transition-colors flex items-center justify-between cursor-pointer ${
                    dateRange === range
                      ? "text-blue-400 bg-blue-500/10 font-semibold"
                      : "text-slate-300 hover:bg-slate-800 hover:text-white"
                  }`}
                >
                  <span>{range}</span>
                  {dateRange === range && <Check className="w-3.5 h-3.5" />}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Action Buttons: Schedule Report + Export Report */}
        <div className="flex items-center gap-2.5">
          <button
            onClick={() => setShowScheduleModal(true)}
            className="px-3.5 py-2 rounded-xl bg-slate-900/80 border border-slate-800 hover:border-slate-700 hover:bg-slate-800/80 text-xs font-medium text-slate-200 flex items-center gap-2 transition-colors cursor-pointer"
          >
            <Clock className="w-3.5 h-3.5 text-slate-400" />
            <span>Schedule Report</span>
          </button>

          <div className="relative">
            <button
              onClick={() => setShowExportDropdown(!showExportDropdown)}
              className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold flex items-center gap-2 transition-colors shadow-lg shadow-blue-600/25 cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Report</span>
              <ChevronDown className="w-3.5 h-3.5 ml-0.5" />
            </button>

            {showExportDropdown && (
              <div className="absolute right-0 top-11 w-48 bg-slate-900 border border-slate-700 rounded-xl shadow-2xl z-30 py-1.5 text-xs animate-fade-in">
                <button
                  onClick={() => handleTriggerExport("pdf")}
                  className="w-full px-3.5 py-2 text-left text-slate-200 hover:bg-slate-800 flex items-center gap-2.5 transition-colors cursor-pointer"
                >
                  <span className="w-5 h-5 rounded bg-rose-500/15 border border-rose-500/30 text-rose-400 flex items-center justify-center font-bold text-[10px]">
                    PDF
                  </span>
                  <span>Export as PDF Document</span>
                </button>
                <button
                  onClick={() => handleTriggerExport("excel")}
                  className="w-full px-3.5 py-2 text-left text-slate-200 hover:bg-slate-800 flex items-center gap-2.5 transition-colors cursor-pointer"
                >
                  <span className="w-5 h-5 rounded bg-emerald-500/15 border border-emerald-500/30 text-emerald-400 flex items-center justify-center font-bold text-[10px]">
                    XLS
                  </span>
                  <span>Export as Excel Sheet</span>
                </button>
                <button
                  onClick={() => handleTriggerExport("powerpoint")}
                  className="w-full px-3.5 py-2 text-left text-slate-200 hover:bg-slate-800 flex items-center gap-2.5 transition-colors cursor-pointer"
                >
                  <span className="w-5 h-5 rounded bg-amber-500/15 border border-amber-500/30 text-amber-400 flex items-center justify-center font-bold text-[10px]">
                    PPT
                  </span>
                  <span>Export as PowerPoint</span>
                </button>
                <button
                  onClick={() => handleTriggerExport("csv")}
                  className="w-full px-3.5 py-2 text-left text-slate-200 hover:bg-slate-800 flex items-center gap-2.5 transition-colors cursor-pointer"
                >
                  <span className="w-5 h-5 rounded bg-blue-500/15 border border-blue-500/30 text-blue-400 flex items-center justify-center font-bold text-[10px]">
                    CSV
                  </span>
                  <span>Export as CSV Data</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Top Banner: Executive Summary (Weekly Infrastructure Report) */}
      <div className="glass-card p-6 rounded-2xl border border-slate-800 relative overflow-hidden bg-gradient-to-r from-slate-900/90 via-slate-900/75 to-blue-950/30">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
          {/* Left Metadata Block */}
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-2xl bg-blue-500/15 border border-blue-500/30 flex items-center justify-center text-blue-400 flex-shrink-0 shadow-inner">
              <FileText className="w-6 h-6" />
            </div>
            <div className="space-y-2">
              <div>
                <h2 className="text-lg font-bold text-white tracking-tight">Executive Summary</h2>
                <p className="text-xs text-slate-400">Weekly Infrastructure Report</p>
              </div>
              <div className="space-y-1 text-xs text-slate-400">
                <div className="flex items-center gap-2">
                  <span className="text-slate-500 w-24">Report Period</span>
                  <span className="font-medium text-slate-200 font-mono">{dateRange}</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-slate-500 w-24">Generated On</span>
                  <span className="font-medium text-slate-200 font-mono">Sep 16, 2026 - 10:30 AM</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-slate-500 w-24">Generated By</span>
                  <span className="font-medium text-slate-200">Secure-MaintAI System</span>
                </div>
              </div>
            </div>
          </div>

          {/* 4 Center Metric Highlights */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 flex-1 lg:max-w-2xl">
            {/* Metric 1: Total Devices */}
            <div className="space-y-1">
              <span className="text-xs text-slate-400 font-medium">Total Devices</span>
              <div className="text-2xl font-bold text-white tracking-tight">
                {kpis.total_devices}
              </div>
              <div className="text-[11px] font-medium text-emerald-400 flex items-center gap-1">
                <span>{kpis.total_devices_change}</span>
              </div>
            </div>

            {/* Metric 2: System Uptime */}
            <div className="space-y-1">
              <span className="text-xs text-slate-400 font-medium">System Uptime</span>
              <div className="text-2xl font-bold text-white tracking-tight">
                {kpis.system_uptime}%
              </div>
              <div className="text-[11px] font-medium text-emerald-400 flex items-center gap-1">
                <span>{kpis.system_uptime_change}</span>
              </div>
            </div>

            {/* Metric 3: Critical Alerts */}
            <div className="space-y-1">
              <span className="text-xs text-slate-400 font-medium">Critical Alerts</span>
              <div className="text-2xl font-bold text-white tracking-tight">
                {kpis.critical_alerts}
              </div>
              <div className="text-[11px] font-medium text-rose-400 flex items-center gap-1">
                <span>{kpis.critical_alerts_change}</span>
              </div>
            </div>

            {/* Metric 4: Security Score */}
            <div className="space-y-1">
              <span className="text-xs text-slate-400 font-medium">Security Score</span>
              <div className="flex items-baseline gap-1">
                <span className="text-2xl font-bold text-white tracking-tight">
                  {kpis.security_score}
                </span>
                <span className="text-xs text-slate-500 font-medium">/100</span>
              </div>
              <div className="text-[11px] font-medium text-emerald-400 flex items-center gap-1">
                <span>{kpis.security_score_change}</span>
              </div>
            </div>
          </div>

          {/* Right Visual 3D Document Illustration Artwork */}
          <div className="hidden xl:flex items-center justify-center pl-4 border-l border-slate-800/80">
            <div className="relative w-28 h-28 flex items-center justify-center">
              <div className="absolute inset-0 bg-blue-500/20 rounded-full blur-2xl pointer-events-none" />
              <svg className="w-24 h-24 drop-shadow-xl" viewBox="0 0 100 100" fill="none">
                <rect x="20" y="10" width="60" height="78" rx="8" fill="#1e293b" stroke="#3b82f6" strokeWidth="2" />
                <rect x="25" y="16" width="30" height="4" rx="2" fill="#64748b" />
                <circle cx="38" cy="38" r="14" fill="#0f172a" stroke="#1e293b" strokeWidth="2" />
                <path d="M38 24 A14 14 0 0 1 52 38 L38 38 Z" fill="#3b82f6" />
                <path d="M52 38 A14 14 0 0 1 42 51 L38 38 Z" fill="#f59e0b" />
                <path d="M42 51 A14 14 0 1 1 38 24 L38 38 Z" fill="#10b981" />
                <line x1="58" y1="30" x2="72" y2="30" stroke="#64748b" strokeWidth="2" strokeLinecap="round" />
                <line x1="58" y1="36" x2="72" y2="36" stroke="#64748b" strokeWidth="2" strokeLinecap="round" />
                <line x1="58" y1="42" x2="68" y2="42" stroke="#64748b" strokeWidth="2" strokeLinecap="round" />
                <rect x="28" y="60" width="4" height="18" rx="1" fill="#3b82f6" />
                <rect x="36" y="66" width="4" height="12" rx="1" fill="#06b6d4" />
                <rect x="44" y="56" width="4" height="22" rx="1" fill="#6366f1" />
                <rect x="52" y="63" width="4" height="15" rx="1" fill="#10b981" />
                <circle cx="72" cy="74" r="12" fill="#2563eb" />
                <path d="M68 74 L71 77 L76 71" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </div>
          </div>
        </div>
      </div>

      {/* Main Grid: 12 Columns (Left 7 cols, Right 5 cols) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
        {/* ================= LEFT COLUMN (7 COLS) ================= */}
        <div className="lg:col-span-7 space-y-5">
          {/* Section 1: Infrastructure Health Overview */}
          <div className="glass-card p-5 rounded-2xl border border-slate-800 space-y-5">
            <div className="flex items-center justify-between pb-2 border-b border-slate-800/80">
              <h3 className="text-sm font-bold text-white tracking-tight">
                1. Infrastructure Health Overview
              </h3>
            </div>

            {/* 4 Mini Summary Cards */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              {/* Online Devices */}
              <div className="p-3 rounded-xl bg-slate-900/70 border border-slate-800/80 flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-blue-500/15 border border-blue-500/30 flex items-center justify-center text-blue-400">
                  <Server className="w-4 h-4" />
                </div>
                <div>
                  <span className="text-[11px] text-slate-400 block">Online Devices</span>
                  <div className="flex items-baseline gap-1.5 mt-0.5">
                    <span className="text-lg font-bold text-white">
                      {MOCK_REPORT_HEALTH_OVERVIEW.online_devices}
                    </span>
                    <span className="text-[11px] text-emerald-400 font-semibold">
                      {MOCK_REPORT_HEALTH_OVERVIEW.online_percentage}%
                    </span>
                  </div>
                </div>
              </div>

              {/* Offline Devices */}
              <div className="p-3 rounded-xl bg-slate-900/70 border border-slate-800/80 flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-rose-500/15 border border-rose-500/30 flex items-center justify-center text-rose-400">
                  <Server className="w-4 h-4" />
                </div>
                <div>
                  <span className="text-[11px] text-slate-400 block">Offline Devices</span>
                  <div className="flex items-baseline gap-1.5 mt-0.5">
                    <span className="text-lg font-bold text-white">
                      {MOCK_REPORT_HEALTH_OVERVIEW.offline_devices}
                    </span>
                    <span className="text-[11px] text-rose-400 font-semibold">
                      {MOCK_REPORT_HEALTH_OVERVIEW.offline_percentage}%
                    </span>
                  </div>
                </div>
              </div>

              {/* Warning Devices */}
              <div className="p-3 rounded-xl bg-slate-900/70 border border-slate-800/80 flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-amber-500/15 border border-amber-500/30 flex items-center justify-center text-amber-400">
                  <AlertTriangle className="w-4 h-4" />
                </div>
                <div>
                  <span className="text-[11px] text-slate-400 block">Warning Devices</span>
                  <div className="flex items-baseline gap-1.5 mt-0.5">
                    <span className="text-lg font-bold text-white">
                      {MOCK_REPORT_HEALTH_OVERVIEW.warning_devices}
                    </span>
                    <span className="text-[11px] text-amber-400 font-semibold">
                      {MOCK_REPORT_HEALTH_OVERVIEW.warning_percentage}%
                    </span>
                  </div>
                </div>
              </div>

              {/* New Devices */}
              <div className="p-3 rounded-xl bg-slate-900/70 border border-slate-800/80 flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-blue-500/15 border border-blue-500/30 flex items-center justify-center text-blue-400">
                  <PlusCircle className="w-4 h-4" />
                </div>
                <div>
                  <span className="text-[11px] text-slate-400 block">New Devices</span>
                  <div className="flex items-baseline gap-1.5 mt-0.5">
                    <span className="text-lg font-bold text-white">
                      {MOCK_REPORT_HEALTH_OVERVIEW.new_devices}
                    </span>
                    <span className="text-[11px] text-blue-400 font-medium">This Week</span>
                  </div>
                </div>
              </div>
            </div>

            {/* System Uptime Trend using Reusable LineChart */}
            <div className="space-y-2 pt-2">
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-slate-300">System Uptime Trend</span>
                <select
                  value={uptimeWindow}
                  onChange={(e) => {
                    const newWin = e.target.value as any;
                    setUptimeWindow(newWin);
                    setFeedbackToast(`Uptime trend window switched to ${newWin}.`);
                    setTimeout(() => setFeedbackToast(null), 2500);
                  }}
                  className="bg-slate-900 border border-slate-700 rounded-lg px-2.5 py-1 text-[11px] text-slate-300 focus:outline-none cursor-pointer"
                >
                  <option value="7 Days">7 Days</option>
                  <option value="14 Days">14 Days</option>
                  <option value="30 Days">30 Days</option>
                </select>
              </div>

              <div className="pt-2">
                <LineChart
                  labels={MOCK_REPORT_UPTIME_TREND.days}
                  data={MOCK_REPORT_UPTIME_TREND.days.map((d, i) => ({
                    label: d,
                    value: MOCK_REPORT_UPTIME_TREND.values[i],
                  }))}
                  height={170}
                  unit="%"
                  color="#3b82f6"
                  onPointClick={(label, idx) => {
                    setFeedbackToast(`Uptime on ${label}: ${MOCK_REPORT_UPTIME_TREND.values[idx]}% (SLA Target met)`);
                    setTimeout(() => setFeedbackToast(null), 3000);
                  }}
                />
              </div>
            </div>
          </div>

          {/* Section 3: Security Posture */}
          <div className="glass-card p-5 rounded-2xl border border-slate-800 space-y-4">
            <div className="flex items-center justify-between pb-2 border-b border-slate-800/80">
              <h3 className="text-sm font-bold text-white tracking-tight">
                3. Security Posture
              </h3>
              <Link
                href="/cybersecurity"
                className="text-xs font-semibold text-blue-400 hover:text-blue-300 transition-colors inline-flex items-center gap-1"
              >
                <span>View all security events</span>
                <span>→</span>
              </Link>
            </div>

            {/* 3 Sparkline Stat Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {/* Security Score Trend */}
              <div className="p-3.5 rounded-xl bg-slate-900/70 border border-slate-800 space-y-2">
                <span className="text-xs text-slate-400 block">Security Score Trend</span>
                <div className="flex items-baseline gap-1">
                  <span className="text-xl font-bold text-white tracking-tight">
                    {MOCK_REPORT_SECURITY_KPIS.security_score}
                  </span>
                  <span className="text-xs text-slate-500 font-medium">/100</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-[11px] text-emerald-400 font-medium">
                    {MOCK_REPORT_SECURITY_KPIS.security_score_change}
                  </span>
                  <svg className="w-20 h-5" viewBox="0 0 80 20">
                    <path
                      d="M 0 16 Q 15 14, 25 12 T 50 8 T 80 4"
                      fill="none"
                      stroke="#3b82f6"
                      strokeWidth="2"
                      strokeLinecap="round"
                    />
                  </svg>
                </div>
              </div>

              {/* Threats Detected */}
              <div className="p-3.5 rounded-xl bg-slate-900/70 border border-slate-800 space-y-2">
                <span className="text-xs text-slate-400 block">Threats Detected</span>
                <div className="text-xl font-bold text-white tracking-tight">
                  {MOCK_REPORT_SECURITY_KPIS.threats_detected}
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-[11px] text-rose-400 font-medium">
                    {MOCK_REPORT_SECURITY_KPIS.threats_detected_change}
                  </span>
                  <svg className="w-20 h-5" viewBox="0 0 80 20">
                    <path
                      d="M 0 18 Q 15 15, 30 14 T 55 10 T 80 3"
                      fill="none"
                      stroke="#ef4444"
                      strokeWidth="2"
                      strokeLinecap="round"
                    />
                  </svg>
                </div>
              </div>

              {/* Vulnerabilities */}
              <div className="p-3.5 rounded-xl bg-slate-900/70 border border-slate-800 space-y-2">
                <span className="text-xs text-slate-400 block">Vulnerabilities</span>
                <div className="text-xl font-bold text-white tracking-tight">
                  {MOCK_REPORT_SECURITY_KPIS.vulnerabilities}
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-[11px] text-emerald-400 font-medium">
                    {MOCK_REPORT_SECURITY_KPIS.vulnerabilities_change}
                  </span>
                  <svg className="w-20 h-5" viewBox="0 0 80 20">
                    <path
                      d="M 0 4 Q 20 8, 40 10 T 60 14 T 80 18"
                      fill="none"
                      stroke="#a855f7"
                      strokeWidth="2"
                      strokeLinecap="round"
                    />
                  </svg>
                </div>
              </div>
            </div>

            {/* Top Threats This Week Table */}
            <div className="pt-1">
              <span className="text-xs font-semibold text-slate-300 block mb-2">
                Top Threats This Week
              </span>
              <div className="overflow-x-auto rounded-xl border border-slate-800/80">
                <table className="w-full text-left text-xs">
                  <thead>
                    <tr className="text-slate-400 border-b border-slate-800 bg-slate-900/50">
                      <th className="py-2.5 px-3 font-semibold">Threat Name</th>
                      <th className="py-2.5 px-3 font-semibold">Severity</th>
                      <th className="py-2.5 px-3 font-semibold">Occurrences</th>
                      <th className="py-2.5 px-3 font-semibold">Status</th>
                      <th className="py-2.5 px-3 font-semibold">First Detected</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-800/50 font-sans">
                    {MOCK_TOP_THREATS_WEEK.map((threat) => (
                      <tr key={threat.id} className="hover:bg-slate-800/30 transition-colors">
                        <td className="py-2.5 px-3 font-medium text-white">
                          <div className="flex items-center gap-2">
                            <Shield className="w-3.5 h-3.5 text-slate-500" />
                            <span>{threat.threat_name}</span>
                          </div>
                        </td>
                        <td className="py-2.5 px-3 whitespace-nowrap">
                          <span
                            className={`px-2 py-0.5 rounded-full text-[10px] font-semibold ${
                              threat.severity === "High"
                                ? "bg-rose-500/15 text-rose-300 border border-rose-500/30"
                                : "bg-amber-500/15 text-amber-300 border border-amber-500/30"
                            }`}
                          >
                            {threat.severity}
                          </span>
                        </td>
                        <td className="py-2.5 px-3 text-slate-300 font-mono">{threat.occurrences}</td>
                        <td className="py-2.5 px-3 whitespace-nowrap">
                          <span
                            className={`px-2 py-0.5 rounded-full text-[10px] font-medium ${
                              threat.status === "Investigating"
                                ? "bg-blue-500/15 text-blue-300 border border-blue-500/30"
                                : threat.status === "Active"
                                ? "bg-amber-500/15 text-amber-300 border border-amber-500/30"
                                : threat.status === "Blocked"
                                ? "bg-rose-500/15 text-rose-300 border border-rose-500/30"
                                : "bg-cyan-500/15 text-cyan-300 border border-cyan-500/30"
                            }`}
                          >
                            {threat.status}
                          </span>
                        </td>
                        <td className="py-2.5 px-3 text-slate-400 whitespace-nowrap">
                          {threat.first_detected}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* Section 5: Resource Utilization */}
          <div className="glass-card p-5 rounded-2xl border border-slate-800 space-y-3">
            <div className="flex items-center justify-between pb-2 border-b border-slate-800/80">
              <h3 className="text-sm font-bold text-white tracking-tight">
                5. Resource Utilization
              </h3>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              {MOCK_RESOURCE_UTILIZATION.map((item) => (
                <div
                  key={item.name}
                  className="p-3 rounded-xl bg-slate-900/60 border border-slate-800 flex items-center justify-between"
                >
                  <div className="flex items-center gap-2.5">
                    <div
                      className="w-7 h-7 rounded-lg flex items-center justify-center"
                      style={{
                        backgroundColor: `${item.color}20`,
                        color: item.color,
                        borderColor: `${item.color}40`,
                        borderWidth: "1px",
                      }}
                    >
                      {item.name === "CPU Usage" ? (
                        <Cpu className="w-3.5 h-3.5" />
                      ) : item.name === "Memory Usage" ? (
                        <Layers className="w-3.5 h-3.5" />
                      ) : item.name === "Disk Usage" ? (
                        <HardDrive className="w-3.5 h-3.5" />
                      ) : (
                        <Activity className="w-3.5 h-3.5" />
                      )}
                    </div>
                    <span className="font-semibold text-slate-200">{item.name}</span>
                  </div>

                  <div className="flex items-center gap-3">
                    <svg className="w-16 h-4" viewBox="0 0 60 16">
                      <path
                        d={`M 0 ${16 - (item.sparkline[0] / 100) * 14} Q 15 ${
                          16 - (item.sparkline[2] / 100) * 14
                        }, 30 ${16 - (item.sparkline[4] / 100) * 14} T 60 ${
                          16 - (item.sparkline[6] / 100) * 14
                        }`}
                        fill="none"
                        stroke={item.color}
                        strokeWidth="2"
                        strokeLinecap="round"
                      />
                    </svg>
                    <span className="font-mono text-slate-300 font-bold whitespace-nowrap">
                      Avg. {item.average}%
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* ================= RIGHT COLUMN (5 COLS) ================= */}
        <div className="lg:col-span-5 space-y-5">
          {/* Section 2: Alerts Overview (Clean DonutChart matching users/page.tsx) */}
          <div className="glass-card p-5 rounded-2xl border border-slate-800 space-y-4">
            <div className="flex items-center justify-between pb-2 border-b border-slate-800/80">
              <h3 className="text-sm font-bold text-white tracking-tight">
                2. Alerts Overview
              </h3>
              <span className="text-[10px] text-slate-400 font-mono">
                {MOCK_REPORT_ALERTS_OVERVIEW.total_alerts} Total Events
              </span>
            </div>

            <div className="flex justify-center my-2">
              <DonutChart
                data={alertsDonutData}
                size={170}
                strokeWidth={18}
                centerLabel={MOCK_REPORT_ALERTS_OVERVIEW.total_alerts}
                centerSub="Total Alerts"
                onSegmentClick={(segment) => {
                  setFeedbackToast(`Selected ${segment.label} alerts (${segment.value} events).`);
                  setTimeout(() => setFeedbackToast(null), 3000);
                }}
              />
            </div>
          </div>

          {/* Section 4: Top Alert Categories */}
          <div className="glass-card p-5 rounded-2xl border border-slate-800 space-y-3.5">
            <div className="flex items-center justify-between pb-2 border-b border-slate-800/80">
              <h3 className="text-sm font-bold text-white tracking-tight">
                4. Top Alert Categories
              </h3>
            </div>

            <div className="space-y-3 pt-1 text-xs">
              {MOCK_TOP_ALERT_CATEGORIES.map((cat) => (
                <div key={cat.category} className="space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="text-slate-300 font-medium">{cat.category}</span>
                    <span className="font-mono font-bold text-white">{cat.count}</span>
                  </div>
                  <div className="w-full bg-slate-900 h-2 rounded-full overflow-hidden border border-slate-800">
                    <div
                      className="h-full rounded-full transition-all duration-500"
                      style={{
                        width: `${(cat.count / 20) * 100}%`,
                        backgroundColor: cat.color,
                      }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 6: Report Summary & Recommendations */}
          <div className="glass-card p-5 rounded-2xl border border-slate-800 space-y-4">
            <div className="flex items-center justify-between pb-2 border-b border-slate-800/80">
              <h3 className="text-sm font-bold text-white tracking-tight">
                6. Report Summary
              </h3>
            </div>

            <p className="text-xs text-slate-300 leading-relaxed">
              Overall, your infrastructure is performing well with high availability and stable
              resources. However, attention is required on high CPU usage and multiple failed login
              attempts to prevent potential risks.
            </p>

            {/* Recommendations Card matching mockup */}
            <div className="p-4 rounded-xl bg-blue-950/20 border border-blue-500/30 space-y-2.5">
              <div className="flex items-center gap-2 text-blue-400 text-xs font-bold">
                <ShieldCheck className="w-4 h-4 text-blue-400" />
                <span>Recommendations</span>
              </div>

              <div className="space-y-2 text-xs">
                {MOCK_REPORT_RECOMMENDATIONS.map((rec, i) => (
                  <div key={i} className="flex items-start gap-2 text-slate-200">
                    <Check className="w-3.5 h-3.5 text-emerald-400 mt-0.5 flex-shrink-0" />
                    <span>{rec}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Row: Report Distribution (Left) & Export Options (Right) */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-5">
        {/* Left: Report Distribution */}
        <div className="md:col-span-6 glass-card p-5 rounded-2xl border border-slate-800 flex items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-blue-500/15 border border-blue-500/30 flex items-center justify-center text-blue-400 flex-shrink-0">
            <Mail className="w-5 h-5" />
          </div>
          <div className="space-y-0.5 text-xs">
            <h4 className="font-bold text-white">Report Distribution</h4>
            <p className="text-slate-400">
              This report is scheduled to be sent to 5 recipients every week.
            </p>
            <p className="text-slate-300 font-mono text-[11px] pt-1">
              Next scheduled report: <span className="text-blue-400 font-semibold">Sep 23, 2026</span>
            </p>
          </div>
        </div>

        {/* Right: Export Options */}
        <div className="md:col-span-6 glass-card p-5 rounded-2xl border border-slate-800 flex flex-col justify-between space-y-2.5">
          <h4 className="text-xs font-bold text-white tracking-tight">Export Options</h4>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
            <button
              onClick={() => handleTriggerExport("pdf")}
              className="px-3 py-2 rounded-xl bg-slate-900 border border-slate-700/80 hover:bg-slate-800 text-slate-200 text-xs font-semibold flex items-center justify-center gap-2 transition-colors cursor-pointer"
            >
              <span className="w-4 h-4 rounded bg-rose-500/20 text-rose-400 flex items-center justify-center font-bold text-[9px]">
                PDF
              </span>
              <span>PDF</span>
            </button>

            <button
              onClick={() => handleTriggerExport("excel")}
              className="px-3 py-2 rounded-xl bg-slate-900 border border-slate-700/80 hover:bg-slate-800 text-slate-200 text-xs font-semibold flex items-center justify-center gap-2 transition-colors cursor-pointer"
            >
              <span className="w-4 h-4 rounded bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold text-[9px]">
                XLS
              </span>
              <span>Excel</span>
            </button>

            <button
              onClick={() => handleTriggerExport("powerpoint")}
              className="px-3 py-2 rounded-xl bg-slate-900 border border-slate-700/80 hover:bg-slate-800 text-slate-200 text-xs font-semibold flex items-center justify-center gap-2 transition-colors cursor-pointer"
            >
              <span className="w-4 h-4 rounded bg-amber-500/20 text-amber-400 flex items-center justify-center font-bold text-[9px]">
                PPT
              </span>
              <span>PowerPoint</span>
            </button>

            <button
              onClick={() => handleTriggerExport("csv")}
              className="px-3 py-2 rounded-xl bg-slate-900 border border-slate-700/80 hover:bg-slate-800 text-slate-200 text-xs font-semibold flex items-center justify-center gap-2 transition-colors cursor-pointer"
            >
              <span className="w-4 h-4 rounded bg-blue-500/20 text-blue-400 flex items-center justify-center font-bold text-[9px]">
                CSV
              </span>
              <span>CSV</span>
            </button>
          </div>
        </div>
      </div>

      {/* Schedule Report Modal */}
      {showScheduleModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fade-in">
          <div className="bg-slate-900 border border-slate-700/90 rounded-2xl w-full max-w-lg p-6 space-y-4 shadow-2xl animate-scale-in">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-xl bg-blue-500/15 border border-blue-500/30 flex items-center justify-center text-blue-400">
                  <Clock className="w-4 h-4" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-white">Schedule Automated Report</h3>
                  <p className="text-xs text-slate-400">Set recurring email delivery for stakeholders</p>
                </div>
              </div>
              <button
                onClick={() => setShowScheduleModal(false)}
                className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-slate-800 cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleSaveSchedule} className="space-y-4 text-xs">
              <div>
                <label className="block font-medium text-slate-300 mb-1">
                  Recipient Email Addresses (comma separated)
                </label>
                <input
                  type="text"
                  required
                  value={scheduleEmail}
                  onChange={(e) => setScheduleEmail(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white placeholder-slate-500 focus:outline-none focus:border-blue-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-medium text-slate-300 mb-1">Cadence</label>
                  <select
                    value={scheduleCadence}
                    onChange={(e) => setScheduleCadence(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-blue-500"
                  >
                    <option value="Daily">Daily Summary</option>
                    <option value="Weekly">Weekly Infrastructure Report</option>
                    <option value="Monthly">Monthly SLA & Security Audit</option>
                  </select>
                </div>

                <div>
                  <label className="block font-medium text-slate-300 mb-1">Delivery Time</label>
                  <input
                    type="text"
                    value={scheduleTime}
                    onChange={(e) => setScheduleTime(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white font-mono focus:outline-none focus:border-blue-500"
                  />
                </div>
              </div>

              <div className="space-y-2 pt-1">
                <span className="block font-medium text-slate-300">Attached File Formats</span>
                <div className="flex items-center gap-4">
                  <label className="flex items-center gap-2 text-slate-300 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={scheduleIncludePdf}
                      onChange={(e) => setScheduleIncludePdf(e.target.checked)}
                      className="rounded border-slate-700 text-blue-600 focus:ring-blue-500"
                    />
                    <span>Executive PDF Document</span>
                  </label>
                  <label className="flex items-center gap-2 text-slate-300 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={scheduleIncludeCsv}
                      onChange={(e) => setScheduleIncludeCsv(e.target.checked)}
                      className="rounded border-slate-700 text-blue-600 focus:ring-blue-500"
                    />
                    <span>Raw CSV Telemetry Data</span>
                  </label>
                </div>
              </div>

              <div className="pt-3 border-t border-slate-800 flex items-center justify-end gap-2.5">
                <button
                  type="button"
                  onClick={() => setShowScheduleModal(false)}
                  className="px-4 py-2 rounded-xl border border-slate-700 text-slate-300 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-semibold shadow-lg shadow-blue-600/25 transition-colors cursor-pointer"
                >
                  Save Schedule
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
